export const setupHtml = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Set up Stackey</title><link rel="stylesheet" href="/setup.css"><script src="/setup.js" defer></script></head>
<body><main><header><span class="mark">S</span><strong>Stackey</strong><span class="local">Local setup</span></header>
<p id="error" class="error" role="alert" hidden></p>
<section id="welcome" hidden><p class="eyebrow">YOUR KEYS. YOUR ACCESS.</p><h1>A wallet<br>that belongs to you.</h1><p>Keep your credentials local. Decide what your agents can do.</p><div class="note"><strong>Recovery takes two things</strong><p>Your 24-word phrase restores your identity. Your encrypted Vault backup restores the passwords and keys you saved.</p></div><label class="check"><input id="understood" type="checkbox">I will keep my recovery phrase private and save encrypted Vault backups.</label><button id="create" class="primary" disabled>Create a new wallet</button><button id="show-restore" class="secondary">Restore a wallet</button><p class="fine">Setup uses a new directory and saves a private local recovery file containing your phrase for terminal unlock. Protect that directory from agents. Existing wallets stay unchanged.</p></section>
<section id="backup" hidden><p class="eyebrow">STEP 1 OF 2</p><h1>Back up your<br>recovery phrase.</h1><p>Write all 24 words in order and keep them offline. Anyone with this phrase and your Vault file can access your credentials. Never share it with an agent.</p><div id="phrase-cover" class="note">Your phrase is hidden.</div><ol id="words" class="words" hidden></ol><button id="reveal" class="secondary">Reveal recovery phrase</button><p class="fine">Hidden after 60 seconds or when you leave this window.</p><label class="check"><input id="saved" type="checkbox">I saved all 24 words in order, somewhere private.</label><button id="to-confirm" class="primary" disabled>Check my backup</button><button id="cancel" class="quiet">Cancel this setup</button></section>
<section id="confirm" hidden><p class="eyebrow">STEP 2 OF 2</p><h1>Check your backup.</h1><p>Enter these words from the backup you just made.</p><form id="confirm-form" autocomplete="off"><div id="challenges"></div><label class="check"><input id="confirmed" type="checkbox">I understand that my phrase alone cannot restore saved passwords. I also need an encrypted Vault backup.</label><button id="finish" class="primary" type="submit" disabled>Finish creating wallet</button></form><button id="back-to-phrase" class="quiet">Back to recovery phrase</button></section>
<section id="restore" hidden><p class="eyebrow">RESTORE YOUR VAULT</p><h1>Bring your<br>wallet back.</h1><p>You need the 24-word phrase and an encrypted Stackey Vault backup. Your existing wallets will not be replaced.</p><form id="restore-form" autocomplete="off"><label for="restore-phrase">Recovery phrase</label><textarea id="restore-phrase" rows="4" autocomplete="off" autocapitalize="none" spellcheck="false" placeholder="Enter 24 words in order" required></textarea><label for="restore-file">Encrypted Vault backup (.json)</label><input id="restore-file" type="file" accept="application/json,.json" required><p class="fine">Up to 4 MiB. Imported passwords cannot be recovered from the phrase alone.</p><label class="check"><input id="restore-confirmed" type="checkbox">Restore into a new wallet. Previous agent grants will not be restored.</label><button id="restore-submit" class="primary" type="submit" disabled>Restore wallet</button></form><button id="restore-back" class="quiet">Back</button></section>
<section id="complete" hidden><span class="success">✓</span><h1 id="complete-title">Your wallet is ready.</h1><p>Save an encrypted backup now, and update it after adding or changing credentials. Store it separately from your recovery phrase.</p><button id="download" class="secondary">Download encrypted backup</button><p id="download-status" role="status" class="fine"></p><button id="open" class="primary">Open wallet</button><details><summary>Local recovery files</summary><p class="fine">For compatibility with the current local unlock workflow, setup saves a private recovery.json file beside the encrypted Vault. It contains your phrase in plaintext. Protect this directory from agents and other users.</p><code id="saved-directory"></code></details><p class="fine">Agents start without permissions. Website login and agent-created credentials are not available yet.</p></section>
<section id="locked" hidden><h1>Setup is locked.</h1><p>Reopen your setup launch URL. If it expired, start setup with a new directory. A completed wallet remains saved on disk.</p></section>
<footer>On this computer · English · No cloud recovery</footer></main></body></html>`;

export const setupCss = `:root{color-scheme:dark;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#f4f1ee;background:#101112;--accent:#ffb4a2;--muted:#b0b5b8}*{box-sizing:border-box}body{margin:0;min-height:100svh;display:grid;place-items:center;padding:24px}main{width:440px;max-width:100%;background:#191a1b;border:1px solid #343638;border-radius:22px;padding:24px}header{display:flex;align-items:center;gap:10px;margin-bottom:36px;font-size:14px}.mark{display:grid;place-items:center;width:34px;height:34px;border-radius:11px;background:var(--accent);color:#322119;font-size:22px;font-weight:700}.local{margin-left:auto;font-size:11px;color:var(--muted)}h1{font-size:32px;line-height:1.17;letter-spacing:-1px;margin:10px 0 18px}p{font-size:13px;line-height:1.7;color:var(--muted)}.eyebrow{font-size:10px;letter-spacing:1.4px}.note{padding:16px;background:#25282a;border:1px solid #343a3d;border-radius:12px;margin:22px 0}.note strong{font-size:13px}.note p{margin-bottom:0}.fine{font-size:11px;line-height:1.7}button{font:inherit;cursor:pointer;min-height:44px;border:0;width:100%;border-radius:24px;padding:12px 16px;margin-top:10px;font-size:13px;font-weight:600}.primary{background:var(--accent);color:#30201b}.secondary{background:#2c3032;color:#f1ebe6}.quiet{background:none;color:#bec4c8}button:disabled{opacity:.4;cursor:not-allowed}label{display:block;font-size:12px;color:#d2d7d9;margin:18px 0 8px}.check{display:flex;align-items:flex-start;gap:10px;line-height:1.7}.check input{margin-top:4px;accent-color:var(--accent);flex-shrink:0}input:not([type=checkbox]),textarea{width:100%;font:inherit;font-size:14px;color:#f4f1ee;padding:12px;background:#131516;border:1px solid #494d50;border-radius:10px}textarea{resize:vertical}input[type=file]{font-size:11px}input:focus-visible,textarea:focus-visible,button:focus-visible,summary:focus-visible{outline:2px solid var(--accent);outline-offset:3px}.words{list-style:none;padding:0;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.words li{padding:10px 6px;background:#25282a;border-radius:7px;font:12px ui-monospace,monospace;overflow-wrap:anywhere}.words span{font-size:10px;color:#939da3;margin-right:5px}.error{background:#40262a;color:#ffc5cf;border:1px solid #72474e;border-radius:10px;padding:12px}.success{display:inline-grid;place-items:center;background:#294335;color:#b6e3c8;border-radius:50%;width:42px;height:42px;font-size:24px}details{margin-top:24px}summary{font-size:12px;color:var(--muted);cursor:pointer}code{font-size:10px;overflow-wrap:anywhere;color:#d1d8dc}footer{margin-top:30px;border-top:1px solid #333638;padding-top:18px;font-size:10px;color:#92999e}[hidden]{display:none!important}@media(max-width:480px){body{padding:0;display:block;background:#191a1b}main{width:100%;min-height:100svh;border:0;border-radius:0;padding:22px}header{margin-bottom:28px}h1{font-size:30px}}`;

export const setupJs = String.raw`'use strict';
const $=id=>document.getElementById(id);
let token=location.hash.slice(1), state, pending=false, wordsTimer, phraseVersion=0;
history.replaceState(null,'','/');
window.addEventListener('hashchange',()=>{if(location.hash)location.reload();});
const errors={setup_locked:'Setup expired. Reopen the launch URL or restart with a new directory.',untrusted_browser:'Open the local setup URL.',confirmation_required:'Read and confirm the recovery requirements.',draft_exists:'Continue or cancel the current setup first.',draft_expired:'The recovery preview expired. Start again.',words_mismatch:'The words do not match. Check your backup and try again.',invalid_recovery:'Enter all 24 recovery words in order.',invalid_vault:'The backup and recovery phrase could not be verified. Check both and try again.',invalid_backup:'Choose an encrypted Stackey backup under 4 MiB.',request_too_large:'The backup is too large. Maximum 4 MiB.',rate_limited:'Too many attempts. Wait one minute before trying again.',output_exists:'This destination already exists. No wallet was replaced.',setup_complete:'This wallet is already saved. Reopen setup to continue.',busy:'Wait for the current operation.'};
function error(message){$('error').textContent=message;$('error').hidden=!message;}
function hideWords(){phraseVersion++;clearTimeout(wordsTimer);$('words').replaceChildren();$('words').hidden=true;$('phrase-cover').hidden=false;$('reveal').textContent='Reveal recovery phrase';}
function clearInputs(){hideWords();$('restore-phrase').value='';$('restore-file').value='';document.querySelectorAll('#challenges input').forEach(input=>input.value='');}
function view(name){hideWords();for(const id of ['welcome','backup','confirm','restore','complete','locked'])$(id).hidden=id!==name;error('');}
async function api(path,data){
 const response=await fetch(path,{method:data===undefined?'GET':'POST',headers:{authorization:'Bearer '+token,...(data===undefined?{}:{'content-type':'application/json'})},...(data===undefined?{}:{body:JSON.stringify(data)}),cache:'no-store',redirect:'error',signal:AbortSignal.timeout(20000)});
 const result=await response.json();if(!response.ok){if(response.status===401){token='';clearInputs();view('locked');}throw new Error(errors[result.error?.code]||'The operation could not be completed. Check setup status before retrying.');}return result.data;
}
function controls(){document.querySelectorAll('button').forEach(b=>b.disabled=pending);$('create').disabled=pending||!$('understood').checked;$('to-confirm').disabled=pending||!$('saved').checked;$('finish').disabled=pending||!$('confirmed').checked;$('restore-submit').disabled=pending||!$('restore-confirmed').checked;}
async function action(fn){if(pending)return;pending=true;controls();error('');try{await fn();}catch(e){error(e.message||'Connection failed. Check the local setup process.');}finally{pending=false;controls();}}
function complete(data){clearInputs();view('complete');$('complete-title').textContent=data.restored?'Your wallet is restored.':'Your wallet is ready.';$('saved-directory').textContent=data.directory||state.directory;}
async function refresh(){state=await api('/api/state');if(state.stage==='complete'){complete({...state.completed,directory:state.directory});}else view(state.stage);}
$('understood').addEventListener('change',controls);$('saved').addEventListener('change',controls);$('confirmed').addEventListener('change',controls);$('restore-confirmed').addEventListener('change',controls);
$('create').onclick=()=>action(async()=>{await api('/api/create',{confirmed:$('understood').checked});await refresh();$('saved').checked=false;});
$('reveal').onclick=()=>action(async()=>{if(!$('words').hidden){hideWords();return;}const version=++phraseVersion;const result=await api('/api/phrase',{draft_id:state.draft_id,confirmed:true});if(version!==phraseVersion||document.hidden||$('backup').hidden||!token)return;const rows=result.words.map((word,i)=>{const li=document.createElement('li'),n=document.createElement('span');n.textContent=String(i+1);li.append(n,document.createTextNode(word));return li;});$('words').replaceChildren(...rows);$('words').hidden=false;$('phrase-cover').hidden=true;$('reveal').textContent='Hide recovery phrase';wordsTimer=setTimeout(hideWords,60000);});
$('to-confirm').onclick=()=>{view('confirm');$('confirmed').checked=false;$('challenges').replaceChildren();for(const position of state.positions){const label=document.createElement('label'),input=document.createElement('input');input.id='word-'+position;input.type='password';input.required=true;input.autocomplete='off';input.spellcheck=false;input.autocapitalize='none';label.htmlFor=input.id;label.textContent='Word '+(position+1);$('challenges').append(label,input);}controls();};
$('back-to-phrase').onclick=()=>{clearInputs();view('backup');};
$('confirm-form').onsubmit=event=>{event.preventDefault();const answers=state.positions.map(p=>$('word-'+p).value);action(async()=>{const result=await api('/api/confirm',{draft_id:state.draft_id,answers,confirmed:$('confirmed').checked});answers.fill('');complete(result);}).finally(()=>{answers.fill('');document.querySelectorAll('#challenges input').forEach(input=>input.value='');});};
$('cancel').onclick=()=>action(async()=>{await api('/api/cancel',{});clearInputs();await refresh();});
$('show-restore').onclick=()=>view('restore');$('restore-back').onclick=()=>{clearInputs();view('welcome');};
$('restore-form').onsubmit=event=>{event.preventDefault();action(async()=>{const file=$('restore-file').files[0];if(!file||file.size>4*1024*1024)throw new Error('Choose an encrypted backup under 4 MiB.');const mnemonic=$('restore-phrase').value;try{const result=await api('/api/restore',{mnemonic,backup:await file.text(),confirmed:$('restore-confirmed').checked});complete(result);}finally{$('restore-phrase').value='';$('restore-file').value='';}});};
$('download').onclick=()=>action(async()=>{const result=await api('/api/backup',{});const url=URL.createObjectURL(new Blob([result.backup],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='stackey-encrypted-backup.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('download-status').textContent='Download requested. Verify the file is saved, and keep it separate from your phrase.';});
$('open').onclick=()=>action(async()=>{const result=await api('/api/open',{});const url=new URL(result.wallet_url);if(url.protocol!=='http:'||url.hostname!=='127.0.0.1')throw new Error('Invalid local wallet destination.');clearInputs();location.assign(url.href);});
window.addEventListener('blur',hideWords);window.addEventListener('pagehide',clearInputs);document.addEventListener('visibilitychange',()=>{if(document.hidden)hideWords();});
setInterval(()=>{if(state&&token&&Date.now()>=state.expires_at*1000){token='';clearInputs();view('locked');}else if(state?.draft_expires_at&&Date.now()>=state.draft_expires_at*1000&&!pending){clearInputs();action(refresh);}},1000);
if(token)action(refresh);else view('locked');
`;
